config/routes.rb
Rails.application.routes.draw do
    get 'patches/favs' => 'patches#favs'
    resources :patches
    resources :ratings

    root 'patches#index'

end

app/models/patch.rb
class Patch < ActiveRecord::Base
    after_save :update_title

    has_many :ratings
    accepts_nested_attributes_for :ratings

    searchkick

    paginates_per 50

    acts_as_taggable # Alias for acts_as_taggable_on :tags
    acts_as_taggable_on :tags

    def search_data
        attributes.merge(tags_name: tags.map(&:name))
    end

    private 
    def update_title
        if self.title == ""
            title = "Patch #" + self.id.to_s
            self.update_column(:title, title)
        end
    end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
    belongs_to :patch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/patches_controller.rb
class PatchesController < ApplicationController
    before_action :set_patch, only: [:show, :edit, :update, :destroy]

    # GET /patches
    # GET /patches.json
    def index
        if params["/patches"].present?
            @patches = Patch.search(params["/patches"][:query])
        else
            #@patches = Patch.all.order(created_at: :desc, average_rating: :desc)
            #@patches = Patch.all.order(created_at: :desc).page(params[:page])
            @patches = Patch.order(created_at: :desc).order(average_rating: :desc).page(params[:page])
        end
        render layout: "patch_index"
=begin
        respond_to do |format|
            format.html # index.html.erb
            format.xml  { render :xml => @patches }
            format.js 
        end
=end
    end

    # GET /patches/1
    # GET /patches/1.json
    def show
    end

    # GET /patches/new
    def new
        @patch = Patch.new
    end

    # GET /patches/1/edit
    def edit
    end

    # POST /patches
    # POST /patches.json
    def create
        @patch = Patch.new(patch_params)

        respond_to do |format|
            if @patch.save
                format.html { redirect_to @patch, notice: 'Patch was successfully created.' }
                format.json { render :show, status: :created, location: @patch }
            else
                format.html { render :new }
                format.json { render json: @patch.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /patches/1
    # PATCH/PUT /patches/1.json
    def update
        respond_to do |format|
            if @patch.update(patch_params)
                format.html { redirect_to @patch, notice: 'Patch was successfully updated.' }
                format.json { render :show, status: :ok, location: @patch }
            else
                format.html { render :edit }
                format.json { render json: @patch.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /patches/1
    # DELETE /patches/1.json
=begin
    def destroy
        @patch.destroy
        respond_to do |format|
            format.html { redirect_to patches_url, notice: 'Patch was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
=end

    # GET /patches/favs
    def favs
        if cookies[:favs]
            @patches = Patch.where(id: cookies[:favs].split(",").map{|x| x.to_i})
        else
            @patches = []
        end
        #puts @patches
        render layout: "patch_index"
    end

    def tag_cloud
        @tags = Patch.tag_counts_on(:tags)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_patch
        @patch = Patch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patch_params
        params.require(:patch).permit(:title, :description, :sub_fifth, :overtone, :ultra_saw, :saw, :pulse_width, :square, :metalizer, :triangle, :cutoff, :mode, :resonance, :env_amt, :brute_factor, :kbd_tracking, :modmatrix, :octave, :volume, :glide, :mod_wheel, :amount, :wave, :rate, :sync, :env_amt_2, :vca, :attack, :decay, :sustain, :release, :pattern, :play, :rate_2, :tag_list)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    before_action :set_rating, only: [:show, :edit, :update, :destroy]

    # GET /ratings
    # GET /ratings.json
    def index
        @ratings = Rating.all
    end

    # GET /ratings/1
    # GET /ratings/1.json
    def show
    end

    # GET /ratings/new
    def new
        @rating = Rating.new
    end

    # GET /ratings/1/edit
    def edit
    end

    # POST /ratings
    # POST /ratings.json
    def create
        @rating = Rating.new(rating_params)

        respond_to do |format|
            if @rating.save
                patch = Patch.find(@rating.patch_id)
                patch.average_rating = patch.ratings.average(:rating)
                patch.save
                format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
                format.json { render :show, status: :created, location: @rating }
            else
                format.html { render :new }
                format.json { render json: @rating.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /ratings/1
    # PATCH/PUT /ratings/1.json
    def update
        respond_to do |format|
            if @rating.update(rating_params)
                format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
                format.json { render :show, status: :ok, location: @rating }
            else
                format.html { render :edit }
                format.json { render json: @rating.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /ratings/1
    # DELETE /ratings/1.json
    def destroy
        @rating.destroy
        respond_to do |format|
            format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
        @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
        #params[:rating, :patch_id]
        params.require(:rating).permit(:rating, :patch_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patches_helper.rb
module PatchesHelper
    include ActsAsTaggableOn::TagsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="Cache-Control" content="max-age=7200">
        <title>BrutalPatches</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

                  ga('create', 'UA-85709129-1', 'auto');
                    ga('send', 'pageview');

        </script>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/layouts/patch_index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="Cache-Control" content="max-age=7200">
        <%= javascript_include_tag 'patch_index', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag "vendor/modernizr" %>
        <%= stylesheet_link_tag    'patch_index', media: 'all', 'data-turbolinks-track' => true %>
        <title>BrutalPatches</title>
        <%= csrf_meta_tags %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

                  ga('create', 'UA-85709129-1', 'auto');
                    ga('send', 'pageview');

        </script>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/patches/_patch.html.erb
<% @patches.each do |patch| %>
    <tr>
        <td class="rating-text">
            <% if patch.average_rating %>
                <%= '★' *  patch.average_rating.to_i %>
            <% end %>
        </td>
        <td><%= link_to patch.title, patch, {class:"orange"} %></td>
        <td class="description-text"><%= patch.description %></td>
    </tr>
<% end %>

app/views/patches/edit.html.erb
<%= render 'edit_form' %>

<%= link_to 'Show', @patch %> |
<%= link_to 'Back', patches_path %>

app/views/patches/favs.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>

<div id="index-patch" class="row">
    <div class="small-12 columns">
        <a href="/"><h1>MICROBRUTE <span class="grey">Patches</span></h1></a>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <p class="grey">Favorites</p>
    </div>
</div>


<div class="row">
    <div class="small-12 columns">
        <div class="infinite-table">
            <table>
                <tbody class="page">
                    <%= render :partial => 'patch', :object => @patches %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <%= link_to 'Back', patches_path, {id: "patch-new"} %>
    </div>
</div>

app/views/patches/index.html.erb
<div class="row">
    <div class="small-12 columns">
        <p id="notice"><%= notice %></p>
    </div>
</div>

<div id="index-patch" class="row">
    <div class="small-8 columns">
        <a href="/"><h1>MICROBRUTE <span class="grey">Patches</span></h1></a>
    </div>
</div>


<div class="row">
    <div class="small-12 columns">
        <%= link_to 'New Patch', new_patch_path, {class: "grey"} %> <span class="orange">|</span> <%= link_to 'Favorites', patches_favs_path, {class: "grey"} %>
    </div>
</div>

<div class="row">
    <div class="small-6 columns">
        <%= form_for(patches_path, {:method => :get}) do |f| %>
            <%= f.text_field :query, :placeholder => "Search..." %>
            <%= submit_tag("Submit", {class: "button tiny"}) %>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <div class="infinite-table">
            <table id="content">
                <tbody class="page">
                    <tr>
                        <th>Rating</th>
                        <th>Title</th>
                        <th>Description</th>
                    </tr>
                    <%= render :partial => 'patch', :object => @patches %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <% unless @patches.current_page == @patches.total_pages %>
            <p id="view-more">
                <%= link_to('View More', url_for(page: @patches.current_page + 1), remote: true) %>
            </p>
        <% end %>
        <!--< paginate @patches, :remote => true > -->
    </div>
</div>

<div class="row">
    <div class="small-12 columns">
        <h5><small class="grey">If you would like to contribute to this site, you will find the source code at <a href="https://github.com/dougsko/brutal_patches">https://github.com/dougsko/brutal_patches</a>.</small></h5>
    </div>
</div>

app/views/patches/index.js.erb
$('#content').append("<%=j render(partial: 'patch', object: @patches) %>");

<% if @patches.current_page == @patches.total_pages %>
      $('#view-more').remove();
<% else %>
    $('#view-more a').attr('href', '<%= url_for(page: @patches.current_page + 1) %>');
<% end %>

app/views/patches/new.html.erb
<%= render 'new_form' %>

app/views/patches/show.html.erb
<p id="notice" class="notice"><%= notice %></p>

<%= render 'show_form' %>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
      <%= f.text_field :rating %>
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>